Blocks:
- IRON_BLOCK 5
- GOLD_BLOCK 10
- DIAMOND_BLOCK 20
Flags:
- use deny
- Entering %player%'s Protection field.
- Leaving %player%'s Protection field.
Region:
  SKYBEDROCK: true
  AUTOHIDE: false
  NODROP: false
  NOSILKTOUCH: true
  LIMIT: -1
Group:
  LIMIT1: 5
  LIMIT2: 10
  LIMIT3: 12
  LIMIT4: 15
  LIMIT5: 17
  LIMIT6: -1
  LIMIT7: 0
  LIMIT8: 0
  LIMIT9: 0
  BLOCKS1: IRON_BLOCK
  BLOCKS2: IRON_BLOCK GOLD_BLOCK
  BLOCKS3: IRON_BLOCK GOLD_BLOCK DIAMOND_BLOCK
  BLOCKS4: IRON_BLOCK GOLD_BLOCK DIAMOND_BLOCK
  BLOCKS5: IRON_BLOCK GOLD_BLOCK DIAMOND_BLOCK
  BLOCKS6: IRON_BLOCK GOLD_BLOCK DIAMOND_BLOCK
  BLOCKS7: IRON_BLOCK GOLD_BLOCK DIAMOND_BLOCK
  BLOCKS8: IRON_BLOCK GOLD_BLOCK DIAMOND_BLOCK
  BLOCKS9: IRON_BLOCK GOLD_BLOCK DIAMOND_BLOCK
Exclusion:
  WORLDS: '[SkyBlock, Liz, Infection]'
  PLACEMENT: false
