ConfigVersion: 1
Integers:
  EngineMode: 2
  UpdateRadius: 2
  InitialRadius: 1
  ProcessingThreads: 1
  MaxLoadedCacheFiles: 64
  ProximityHiderDistance: 8
  ProximityHiderID: 0
  ProximityHiderEnd: 255
Booleans:
  UseProximityHider: true
  UseSpecialBlockForProximityHider: true
  UpdateOnBreak: true
  UpdateOnDamage: true
  UpdateOnPhysics: true
  UpdateOnPiston: true
  UpdateOnExplosion: true
  UpdateOnHoe: true
  UpdateThread: true
  DarknessHideBlocks: true
  VerboseMode: false
  NoObfuscationForOps: true
  NoObfuscationForPermission: true
  UseCache: false
  Enabled: true
Lists:
  ObfuscateBlocks:
  - 14
  - 15
  - 16
  - 21
  - 54
  - 56
  - 73
  - 74
  DarknessObfuscateBlocks:
  - 52
  - 54
  ProximityHiderBlocks:
  - 23
  - 54
  - 58
  - 61
  - 62
  - 116
  RandomBlocks:
  - 5
  - 14
  - 15
  - 16
  - 21
  - 48
  - 56
  - 73
  DisabledWorlds: []
