#
# WorldGuard's world configuration file
#
# This is a world configuration file. Anything placed into here will only
# affect this world. If you don't put anything in this file, then the
# settings will be inherited from the main configuration file.
#
# If you see {} below, that means that there are NO entries in this file.
# Remove the {} and add your own entries.
#

regions:
    max-region-count-per-player:
        default: 0
    claim-only-inside-existing-regions: false
    invincibility-removes-mobs: false
    max-claim-volume: 30000
    high-frequency-flags: true
    enable: true
    use-scheduler: true
    wand: 287
