chat-range: 100.0
display-name-format: '%prefix%player%suffix'
global-message-format: <%prefix%player%suffix> &e%message
enable: false
message-format: <%prefix%player%suffix> %message
ranged-mode: false
