
# Give operators (set with the Minecraft /op command) all permissions.
op-permissions: true

# Use users' display names rather than than their raw username in various messages. Display names are set by other plugins.
use-display-names: true
item-names:
    goldblock: 41
    ice: 79

# For /time, /weather, and other commands, broadcast change messages to everyone when you change world information with the commands.
broadcast-changes: true

# Disables some features to be compatible with badly-written server wrappers.
crappy-wrapper-compat: true

# Configurations for CommandBook's built-in components are stored here.
# Custom component configurations are stored as individual files in the the config/ folder
component:
    online-list:
        colored-names: false
        grouped-names: false
        show-max-players: true
        list-on-join: true
    stored-messages:
        motd: |
            Hello, `Y%name%`w.
            The time now is `Y%time%`w in '%world%'.
        rules: |
            - Treat the staff well and they will be glad to help.
            - Treating staff poorly will guarantee you wont get what you want.
            - Mostly anything goes, just no spawncamping or harassing people.
            - Be courteous and respect others.
            - Don't use any tools to give you an unfair advantage.
    inventory:
        item-permissions-only: false
        disallowed-items: []
        allowed-items: []
        default-item-stack-size: 1
        disllowed-items: []
    thor:
        hammer-items:
        - 278
        - 285
        - 257
        - 270
    bans:
        broadcast-bans: false
        '&': false
        message: You have been banned
        broadcast-kicks: false
    messaging:
        console-say-format: <`rIridious`w> %s
        broadcast-format: '`r[ImportantBroadcast] %s'
        twitter-style: true
    spawn-locations:
        exact-spawn: true
    time-control:
        time-lock-delay: 20
        time-lock:
    warps:
        per-world: false
    homes:
        per-world: false
    god:
        auto-enable: false

# Similar to use-display-names, this allows usage of users' display names when looking up players.
lookup-with-display-names: true

# When this setting is enabled, CommandBook's commands will be registered AFTER every 
# other plugin's commands. If any other plugin registers a command that conflicts with
# one of CommandBook's commands, the CommandBook command will be accessible with 
# /commandbook:<command>, and the other plugin's command will be accessible 
# with /<command>
low-priority-command-registration: false

# A list of enabled and disabled components. Components in the disabled list 
# will automatically be removed from the enabled list. Fully qualified class names can 
# or aliases (automatically added to the list by CommandBook) can be used as component names.
components:
    disabled:
    - freeze
    - help
    - homes
    - warps
    - god
    enabled:
    - bans
    - messaging
    - teleport
    - items
    - kits
    - midi
    - time
    - name-verification
    - fun
    - debug
    - thor
    - online-list
    - stored-messages
    - spawn-locations
    - info
    - world
    - player
